// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6EkM4OIgfIfYn7xW5bXHkjKcYaBFNIWg',
    appId: '1:279191939131:web:4e59e36ce5682a8d04541e',
    messagingSenderId: '279191939131',
    projectId: 'vidyusaathi',
    authDomain: 'vidyusaathi.firebaseapp.com',
    storageBucket: 'vidyusaathi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGwb51UOf9Y9boqNxWwYbf1uZG-h6edH0',
    appId: '1:279191939131:android:ca72521a0fbb4f9d04541e',
    messagingSenderId: '279191939131',
    projectId: 'vidyusaathi',
    storageBucket: 'vidyusaathi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB73amKrAGtP1D-f7SYj9XDH9rnFB2GP90',
    appId: '1:279191939131:ios:a2dbf84b89ff7da304541e',
    messagingSenderId: '279191939131',
    projectId: 'vidyusaathi',
    storageBucket: 'vidyusaathi.firebasestorage.app',
    iosBundleId: 'com.mahavitran.vidyusaathi.vidyusaathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB73amKrAGtP1D-f7SYj9XDH9rnFB2GP90',
    appId: '1:279191939131:ios:a2dbf84b89ff7da304541e',
    messagingSenderId: '279191939131',
    projectId: 'vidyusaathi',
    storageBucket: 'vidyusaathi.firebasestorage.app',
    iosBundleId: 'com.mahavitran.vidyusaathi.vidyusaathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'dummy-api-key',
    appId: 'dummy-app-id',
    messagingSenderId: 'dummy-sender-id',
    projectId: 'vidyusaathi-dummy',
    storageBucket: 'vidyusaathi-dummy.appspot.com',
    authDomain: 'vidyusaathi-dummy.firebaseapp.com',
  );
}

